Fest.WebUI/Areas/Admin/Controllers/CityController.cs
using Fest.Business.Dtos.City;
using Fest.Business.Services;
using Fest.WebUI.Areas.Admin.Models.ViewModel.CityViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using X.PagedList;

namespace Fest.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class CityController : Controller
    {

        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;

        public CityController(ICityService cityService, ICountryService countryService)
        {
            _cityService = cityService;
            _countryService = countryService;
        }

        public IActionResult List(string search, int page=1)
        {
            

            if (string.IsNullOrWhiteSpace(search))
            {
                var cityDtos = _cityService.GetCityList();

                var viewModel = cityDtos.Select(x => new CityListVM
                {
                    Id = x.Id,
                    CountryName = x.CountryName,
                    Name = x.Name,
                    CreatedDate = x.CreatedDate,
                    Description = x.Description
                }).ToList().ToPagedList();


                ViewBag.cityCount=viewModel.Count;

                return View(viewModel);
            }
            else
            {
                var searchCity=_cityService.GetCitySearch(search);

                var searchViewModel = searchCity.Select(x => new CityListVM
                {
                    Id = x.Id,
                    CountryName = x.CountryName,
                    Name = x.Name,
                    CreatedDate = x.CreatedDate,
                    Description = x.Description
                }).ToList().ToPagedList();

                ViewBag.cityCount=searchViewModel.Count;

                return View(searchViewModel);

            }
     
        }
        [HttpGet]
        public IActionResult New()
        {
            ViewBag.countries=_countryService.GetCountries();

            return View("Form",new CityAddOrUpdateVM());
        }
        [HttpPost]
        public IActionResult Save(CityAddOrUpdateVM formData)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.countries = _countryService.GetCountries();

                return View("Form", formData);
            }
            else
            {

                if (formData.Id == 0)
                {
                    var cityDto = new CityDto
                    {
                        Name = formData.Name,
                        CountryId = formData.CountryId,
                        Description = formData.Description,
                    };

                    var response = _cityService.AddCity(cityDto);

                    if (response.IsSucceed)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ViewBag.errorMessage = response.Message;
                        ViewBag.countries = _countryService.GetCountries();
                        return View("Form", formData);
                    }
                }
                else
                {

                    var cityDto = new CityEditDto()
                    {
                        Id = formData.Id,
                        Name = formData.Name,
                        Description = formData.Description,
                        CountryId = formData.CountryId
                    };

                    _cityService.EditCity(cityDto);

                    return RedirectToAction("List");

                }

                

                
            }
        }

        public IActionResult Edit(int id)
        {
            var CityDto=_cityService.GetCityById(id);

            var viewModel = new CityAddOrUpdateVM()
            {
                Id = CityDto.Id,
                Name = CityDto.Name,
                Description = CityDto.Description,
                CountryId = CityDto.CountryId
            };

            ViewBag.countries = _countryService.GetCountries();

            return View("Form", viewModel);


        }
       
        public IActionResult Delete(int id)
        {

            _cityService.DeleteCity(id);

            return RedirectToAction("List");

        }


        public IActionResult Detail(int id)
        {

            var cityDto=_cityService.GetCityDetailById(id);

            var viewModel = new CityDetailVM()
            {
                Id = cityDto.Id,
                Name = cityDto.Name,
                CreatedDate = cityDto.CreatedDate,
                Description = cityDto.Description,
                IsActive = cityDto.IsActive,
                CountryName = cityDto.Name

            };

            return PartialView(viewModel);
        }

        

    }
}

Fest.WebUI/Areas/Admin/Controllers/FestController.cs
using Fest.Business.Dtos.Fest;
using Fest.Business.Services;
using Fest.WebUI.Areas.Admin.Models.ViewModel.FestViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient.Server;
using System.Data;
using X.PagedList;

namespace Fest.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class FestController : Controller
    {
        private readonly IFestService _FestService;

        private readonly ICityService _CityService;

        private readonly IWebHostEnvironment _environment;

        public FestController(IFestService festService, ICityService cityService, IWebHostEnvironment environment)
        {
            _FestService = festService;
            _CityService = cityService;
            _environment = environment;
        }


        public IActionResult List(string search,int page=1)
        {


            var countList = 0;
            

            if (!string.IsNullOrEmpty(search))
            {
                


                var searchList = _FestService.GetFestSearchList(search);

                var searchViewModels = searchList.Select(x => new FestListVM
                {
                    Id = x.Id,
                    CityName = x.CityName,
                    CountryName = x.CountryName,
                    CreatedDate = DateTime.Now,
                    FestName = x.FestName,
                    ImagePath = x.ImagePath,
                    TicketPrice = x.TicketPrice,
                }).ToList().ToPagedList(page,5);

                countList = searchViewModels.Count();

                ViewBag.Count = countList;
                

                return View(searchViewModels);
            }
            else
            {

                var dtoList = _FestService.GetFestList();

                var viewModels = dtoList.Select(x => new FestListVM
                {
                    Id = x.Id,
                    FestName = x.FestName,
                    CityName = x.CityName,
                    CountryName = x.CountryName,
                    CreatedDate = x.CreatedDate,
                    ImagePath = x.ImagePath,
                    TicketPrice = x.TicketPrice
                }).ToList().ToPagedList(page,5);

                countList = viewModels.Count();

                ViewBag.Count = countList;

                return View(viewModels);
            }


           
        }
        [HttpGet]
        public IActionResult New(int? id)
        {
            if (id != null)
            {
                var fest = _FestService.GetFestById(id.Value);

                var viewModel = new FestAddOrUpdateVM
                {
                    Id = fest.Id,
                    FestName = fest.FestName,
                    Description = fest.Description,
                    CityId = fest.CityId,
                    StartDate = fest.StartDate,
                    EndDate = fest.EndDate,
                    Location = fest.Location,
                    TicketPrice = fest.TicketPrice
                };

                ViewBag.imagePath = fest.ImagePath;

                ViewBag.cities = _CityService.GetCityList();

                return View("Form", viewModel);



            }
            else
            {
                ViewBag.cities = _CityService.GetCityList();

                return View("Form", new FestAddOrUpdateVM());
            }


        }
        [HttpPost]
        public IActionResult Save(FestAddOrUpdateVM formData)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.cities = _CityService.GetCityList();

                return View("Form", formData);
            }
            var newFileName = "";


            if (formData.File != null)
            {
                var allowedFileContentTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };

                var allowedFileExtensions = new string[] { ".jpeg", ".png", ".jpg", ".jfif" };


                var fileContentType = formData.File.ContentType;

                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(formData.File.FileName);

                var fileExtension = Path.GetExtension(formData.File.FileName);

                if (!allowedFileContentTypes.Contains(fileContentType) || !allowedFileExtensions.Contains(fileExtension))
                {

                    ViewBag.fileError = "Lütfen jpg jpeg png jfif uzantılı bir dosya türü seçiniz";

                    return View("Form", formData);
                }

                newFileName = fileNameWithoutExtension + "-" + Guid.NewGuid() + fileExtension;

                var folderPath = Path.Combine("images", "fests");

                var wwwRootFolderPath = Path.Combine(_environment.WebRootPath, folderPath);

                var wwwRootFilePath = Path.Combine(wwwRootFolderPath, newFileName);


                Directory.CreateDirectory(wwwRootFolderPath);

                using (var fileStream = new FileStream(wwwRootFilePath, FileMode.Create))
                {
                    formData.File.CopyTo(fileStream);
                }

            }

            if (formData.Id == 0)
            {
                var festAddDto = new FestAddOrUpdateDto
                {
                    Id = formData.Id,
                    FestName = formData.FestName,
                    CityId = formData.CityId,
                    StartDate = formData.StartDate,
                    EndDate = formData.EndDate,
                    Description = formData.Description,
                    Location = formData.Location,
                    TicketPrice = formData.TicketPrice,
                    ImagePath = newFileName
                };

                var response = _FestService.AddFest(festAddDto);

                if(response.IsSucceed)
                {
                    return RedirectToAction("List");
                }
                else
                {
                    ViewBag.errorMessage = response.Message;

                    return View("Form", formData);
                }

            }
            else
            {
                var festEditDto = new FestAddOrUpdateDto
                {
                    Id = formData.Id,
                    FestName = formData.FestName,
                    CityId = formData.CityId,
                    StartDate = formData.StartDate,
                    EndDate = formData.EndDate,
                    Description = formData.Description,
                    Location = formData.Location,
                    TicketPrice = formData.TicketPrice,

                };

                if(formData.File!=null)
                {
                    festEditDto.ImagePath = newFileName;

                    _FestService.EditFest(festEditDto);

                    return RedirectToAction("List");
                }

            }


            return View();
        }

        public IActionResult Delete(int id)
        {
            _FestService.DeleteFest(id);

            return RedirectToAction("List");
        }


        public IActionResult Detail(int id)
        {
            var dto=_FestService.GetFestDetail(id);

            var viewModel = new FestDetailVM
            {
                Id = dto.Id,
                FestName = dto.FestName,
                CityName = dto.CityName,
                CountryName = dto.CountryName,
                StartDate = dto.StartDate,
                EndDate = dto.EndDate,
                CreatedDate = dto.CreatedDate,
                Description = dto.Description,
                FestDuration = dto.FestDuration,
                Location = dto.Location,
                Time = dto.Time,
                TicketPrice = dto.TicketPrice,
                IsActive = dto.IsActive
                
            };


            return PartialView(viewModel);
        }

    }
}

Fest.WebUI/Controllers/FestController.cs
using Fest.Business.Dtos.Comment;
using Fest.Business.Services;
using Fest.WebUI.Extensions;
using Fest.WebUI.Models.ViewModel.CommentVM;
using Fest.WebUI.Models.ViewModel.FestVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Fest.WebUI.Controllers
{
    public class FestController : Controller
    {
        private readonly IFestService _festService;

        private readonly IFestArtistService _festArtistService;

        private readonly ICommentService _commentService;

        public FestController(IFestService festService, IFestArtistService festArtistService, ICommentService commentService)
        {
            _festService = festService;
            _festArtistService = festArtistService;
            _commentService = commentService;
        }


        public IActionResult List()
        {
            var dtos = _festService.GetFestList();


            var firstFest = _festService.GetFestFirstData();


            ViewBag.firstData = firstFest;

            var viewModels = dtos.Select(x => new FestListVM
            {
                Id = x.Id,
                StartDate = x.StartDate,
                FestName = x.FestName,
                ImagePath = x.ImagePath,
                Description = x.Description,
                TicketPrice = x.TicketPrice,
                CityName = x.CityName,
                CountryName = x.CountryName

            }).ToList();


            return View(viewModels);
        }

        public IActionResult Detail(int id)
        {

            var festDetail = _festArtistService.GetFestArtistFullDetail(id);

            var viewModel = new FestArtistFullDetailVM
            {
                Id = id,

                FestName = festDetail.FestName,
                CityName = festDetail.CityName,
                CountryName = festDetail.CountryName,
                StartDate = festDetail.StartDate,
                EndDate = festDetail.EndDate,
                Description = festDetail.Description,
                Location = festDetail.Location,
                TicketPrice = festDetail.TicketPrice,
                IsActive = festDetail.IsActive,
                Artists = festDetail.Artists,
                ImagePath = festDetail.ImagePath,
                FestId = festDetail.FestId
            };


            return View(viewModel);
        }

        [Authorize(Roles = "admin, user")]
        [HttpPost]
        public IActionResult Comment(int festId, string content)
        {



            var userId = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value);

            var firstName = User.Claims.FirstOrDefault(x => x.Type == "firstName")?.Value;

            var lastName = User.Claims.FirstOrDefault(x => x.Type == "lastName")?.Value;

            var dto = new CommentDto
            {

                FestId = festId,
                AuthorName = firstName + " " + lastName,
                Status = false,
                Content = content,
                UserId = userId


            };


            _commentService.Comment(dto);

            return RedirectToAction("Detail", new { id = festId });
        }


    }
}

Fest.WebUI/Areas/Admin/Views/Fest/Detail.cshtml
@model FestDetailVM



<div class="modal-header">

    @if (Model.IsActive)
    {
        <h6 style="color:green">Aktif Kayıt</h6>
    }
    else
    {
        <h6 style="color:red">Kayıt Aktif Değil</h6>
    }

    <hr />





    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>



</div>
<div class="modal-body">

    <h6>
        Festivalin Oluşturulma Tarihi : @Model.CreatedDate
    </h6>

    <br />

    <h6>Festival : @Model.FestName</h6>

    <br />

    

    <h6>Ülke - Festival : @Model.CountryName</h6>

    <br />

    <h6>Şehir - Festival : @Model.CityName</h6>

    <br />

    <h6>Festival Başlangıç Tarihi : @Model.StartDate.ToShortDateString()</h6>

    <br />

    <h6>Festival Süresi : @Model.FestDuration</h6>

    <br />

    <h6>Festivalin Başlamasına @Model.Time gün var</h6>

    <br />

    <h6>Bilet Fiyatı : @Model.TicketPrice</h6>

    <br />








    <hr />

    <h6>Festival Lokasyonu : @Model.Location</h6>

    <br />

    <p>
        <b class="text-secondary">Açıklaması : @Model.Description</b>
    </p>

</div>

Fest.WebUI/Areas/Admin/Views/Fest/Form.cshtml
@model FestAddOrUpdateVM


<div class="container" style="padding-top:40px">

    <div class="row">

        <div class="col-md-8 offset-2">

            <div class="card" style="border:solid 2px">

                <div class="card-header fw-bold fs-5" style="text-align:center">

                    @(Model.Id == 0 ? "Festival Ekleme Formu" : "Festival Düzenleme Formu")
                </div>

                <div class="card-body">

                    <form method="post" asp-area="Admin" asp-controller="Fest" asp-action="Save" enctype="multipart/form-data">



                        @if (!string.IsNullOrWhiteSpace(ViewBag.errorMessage))
                        {

                            <div class="alert alert-danger">
                                @ViewBag.errorMessage
                            </div>

                        }

                        <input asp-for="Id" type="hidden" />


                        <div class="form-group mb-2">

                            <label asp-for="FestName"></label>

                            <input asp-for="FestName" class="form-control" type="text" />

                            <span class="text-danger fw-bold" asp-validation-for="FestName"></span>

                        </div>

                        

                        <div class="form-group mb-2">

                            <label asp-for="CityId"></label>

                            <select asp-items="@(new SelectList(ViewBag.cities,"Id","Name"))" class="form-control" type="text"
                                    asp-for="CityId">
                            </select>

                            <span asp-validation-for="CityId" class="text-danger fw-bold"></span>

                            

                        </div>



                        <div class="form-group mb-2">

                            <label asp-for="StartDate"></label>

                            <input asp-for="StartDate" class="form-control" type="date" />

                            <span asp-validation-for="StartDate" class="text-danger fw-bold"></span>

                        </div>

                        <div class="form-group mb-2">

                            <label asp-for="EndDate"></label>

                            <input asp-for="EndDate" class="form-control" type="date" />

                            <span asp-validation-for="EndDate" class="text-danger fw-bold"></span>

                        </div>


                        <div class="form-group mb-2">

                            <label asp-for="TicketPrice"></label>

                            <input asp-for="TicketPrice" class="form-control" type="number" />

                            <span class="text-danger fw-bold" asp-validation-for="TicketPrice"></span>

                        </div>


                        <div class="form-group">

                            <label asp-for="Location"></label>

                            <textarea asp-for="Location" class="form-control">

                            </textarea>

                            <span asp-validation-for="Location" class="text-danger fw-bold"></span>

                        </div>


                        <div class="form-group">

                            <label asp-for="Description"></label>

                            <textarea asp-for="Description" class="form-control">

                            </textarea>

                            <span asp-validation-for="Description" class="text-danger fw-bold"></span>

                        </div>


                        <div class="form-group mb-2">

                            <label asp-for="File"></label>

                            @if (Model.Id != 0)
                            {
                                @if (string.IsNullOrWhiteSpace(@ViewBag.ImagePath))
                                {
                                    <div>

                                        <img src="~/images/fests/@ViewBag.imagePath" style="width:200px; height:200px" />

                                    </div>
                                }
                                else
                                {
                                    <div>

                                        <img src="~/images/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg"
                                             style="width:200px; height:200px" />

                                    </div>
                                }
                            }


                            <input asp-for="File" type="file" class="form-control" />

                            <span asp-validation-for="File" class="text-danger fw-bold"></span>

                        </div>


                        <button type="submit" class="btn btn-success mt-3 float-end">
                            @(Model.Id == 0 ? "Ekle" : "Güncelle")
                        </button>

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>

Fest.WebUI/Areas/Admin/Views/Fest/List.cshtml
@model IPagedList<FestListVM>

<div class="container">

    <div class="row">

        <div class="col-sm-11">


            <div>

                <div class="text-center">

                    <h2 style="font-family:Calibri" class="text-secondary">Festivaller</h2>

                </div>






                <div style="padding-top:50px">


                    <div style="margin-bottom:15px">


                        <div class="float-start">
                            <form>
                                <div class="btn-group">
                                    <input class="form-control" type="text" placeholder="Arama Yap ...." name="search" style="display: inline-block; width: 80%;" />
                                    <input class="p-2 ml-3 btn btn-sm btn-primary" type="submit" value="Ara" style="display: inline-block; width: 20%;" />
                                </div>
                            </form>

                        </div>

                    </div>

                    <div class="float-end">


                        <a asp-area="Admin" asp-controller="Fest" asp-action="New" class="btn btn-link">

                            <i class="bi bi-plus-circle-fill"></i>

                            Yeni Festival
                        </a>

                    </div>


                    <table id="myTable" class="table table-bordered table-striped">

                        <thead>
                            <tr>
                                <th>#</th>
                                <th></th>
                                <th>Festival</th>
                                <th>Festival Ülkesi</th>
                                <th>Festival Şehir</th>
                                <th>Oluşturulma Tarihi</th>
                                <th>Bilet Fiyatı</th>

                            </tr>
                        </thead>

                        <tbody>
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>

                                    <td>

                                        @if (string.IsNullOrWhiteSpace(Model[i].ImagePath))
                                        {
                                            <img style="width:100px;height:100px" src="~/images/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg" />
                                        }
                                        else
                                        {
                                            <a style="width:80px;height:80px" href="~/images/artists/@Model[i].ImagePath" data-lightbox="@Model[i].Id" data-title="@Model[i].FestName">

                                                <img src="~/images/fests/@Model[i].ImagePath" alt="@Model[i].FestName" style="width:100px;height:100px" />

                                            </a>
                                        }

                                    </td>


                                    <td>@Model[i].FestName</td>
                                    <td>@Model[i].CountryName</td>
                                    <td>@Model[i].CityName</td>
                                    <td>@Model[i].CreatedDate</td>
                                    <td>@Model[i].TicketPrice</td>

                                    <td>

                                        <button style="margin-left:40px" class="btn btn-sm btn-secondary modalButton" data-id="@Model[i].Id" data-target="modal-lg">
                                            <i class="bi-search">Detay</i>



                                        </button>

                                        <a style="margin-left:3px" asp-area="Admin" asp-controller="Fest" asp-action="New" asp-route-id="@Model[i].Id" class="btn btn-sm btn-primary">
                                            <i class="bi bi-pencil-square">Düzenle</i>
                                        </a>
                                        <a style="margin-left:3px" data-id="@Model[i].Id" class="btn btn-sm btn-danger delete">
                                            <i class="bi bi-trash3">Sil</i>
                                        </a>




                                        

                                    </td>

                                </tr>
                            }


                        </tbody>

                    </table>

                    <p class="text-secondary">Toplam : @ViewBag.Count Kayıt Bulundu. </p>


                    <div style="margin-top:30px">

                        <div class="col-md-3
                        " style="margin-left:auto;text-align:right">

                        @Html.PagedListPager((IPagedList)Model,page=>Url.Action("List","City",new {page=page}),
                        new PagedListRenderOptions {

                        LiElementClasses=new List<string>
                        {"page-link"}
                        })




                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>





@section Scripts{


    <script>


        $(".modalButton").click(function () {
            // AJAX isteği yapın

            var festId = $(this).data("id")

            $.ajax({
                url: "/Admin/Fest/Detail/" + festId,
                type: "GET",
                success: function (result) {
                    // Detail sayfasındaki içeriği alın
                    $("#modalContent").html(result);
                    // Modalı açın
                    $("#modalContainer").modal("show");
                }
            });
        });


        $('#myTable .delete').click(function (e) {

            e.preventDefault();

            var FestId = $(this).data('id');

            Swal.fire({
                title: 'Emin misin?',
                text: "Dikkat ! Kayıt silinecektir.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Onaylıyorum.',
                cancelButtonText: "İptal"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: '/Admin/Fest/Delete/' + FestId,
                        method: "GET"
                    }).done(function () {

                        Swal.fire(
                            'Silindi!',
                            'Bir Kayıt Başarıyla Silindi.',
                            'success'
                        ).then(() => { window.location.reload() }
                        );
                    }).fail(function () {

                        Swal.fire("Hata!", "Bir hata oluştu, Kayıt silinemedi.", "error")
                    });


                }
            })

        });


    </script>
}