Fest.WebUI/Areas/Admin/Controllers/FestController.cs
using Fest.Business.Dtos.Fest;
using Fest.Business.Services;
using Fest.WebUI.Areas.Admin.Models.ViewModel.FestViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient.Server;
using System.Data;
using X.PagedList;

namespace Fest.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class FestController : Controller
    {
        private readonly IFestService _FestService;

        private readonly ICityService _CityService;

        private readonly IWebHostEnvironment _environment;

        public FestController(IFestService festService, ICityService cityService, IWebHostEnvironment environment)
        {
            _FestService = festService;
            _CityService = cityService;
            _environment = environment;
        }


        public IActionResult List(string search,int page=1)
        {


            var countList = 0;
            

            if (!string.IsNullOrEmpty(search))
            {
                


                var searchList = _FestService.GetFestSearchList(search);

                var searchViewModels = searchList.Select(x => new FestListVM
                {
                    Id = x.Id,
                    CityName = x.CityName,
                    CountryName = x.CountryName,
                    CreatedDate = DateTime.Now,
                    FestName = x.FestName,
                    ImagePath = x.ImagePath,
                    TicketPrice = x.TicketPrice,
                }).ToList().ToPagedList(page,5);

                countList = searchViewModels.Count();

                ViewBag.Count = countList;
                

                return View(searchViewModels);
            }
            else
            {

                var dtoList = _FestService.GetFestList();

                var viewModels = dtoList.Select(x => new FestListVM
                {
                    Id = x.Id,
                    FestName = x.FestName,
                    CityName = x.CityName,
                    CountryName = x.CountryName,
                    CreatedDate = x.CreatedDate,
                    ImagePath = x.ImagePath,
                    TicketPrice = x.TicketPrice
                }).ToList().ToPagedList(page,5);

                countList = viewModels.Count();

                ViewBag.Count = countList;

                return View(viewModels);
            }


           
        }
        [HttpGet]
        public IActionResult New(int? id)
        {
            if (id != null)
            {
                var fest = _FestService.GetFestById(id.Value);

                var viewModel = new FestAddOrUpdateVM
                {
                    Id = fest.Id,
                    FestName = fest.FestName,
                    Description = fest.Description,
                    CityId = fest.CityId,
                    StartDate = fest.StartDate,
                    EndDate = fest.EndDate,
                    Location = fest.Location,
                    TicketPrice = fest.TicketPrice
                };

                ViewBag.imagePath = fest.ImagePath;

                ViewBag.cities = _CityService.GetCityList();

                return View("Form", viewModel);



            }
            else
            {
                ViewBag.cities = _CityService.GetCityList();

                return View("Form", new FestAddOrUpdateVM());
            }


        }
        [HttpPost]
        public IActionResult Save(FestAddOrUpdateVM formData)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.cities = _CityService.GetCityList();

                return View("Form", formData);
            }
            var newFileName = "";


            if (formData.File != null)
            {
                var allowedFileContentTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };

                var allowedFileExtensions = new string[] { ".jpeg", ".png", ".jpg", ".jfif" };


                var fileContentType = formData.File.ContentType;

                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(formData.File.FileName);

                var fileExtension = Path.GetExtension(formData.File.FileName);

                if (!allowedFileContentTypes.Contains(fileContentType) || !allowedFileExtensions.Contains(fileExtension))
                {

                    ViewBag.fileError = "Lütfen jpg jpeg png jfif uzantılı bir dosya türü seçiniz";

                    return View("Form", formData);
                }

                newFileName = fileNameWithoutExtension + "-" + Guid.NewGuid() + fileExtension;

                var folderPath = Path.Combine("images", "fests");

                var wwwRootFolderPath = Path.Combine(_environment.WebRootPath, folderPath);

                var wwwRootFilePath = Path.Combine(wwwRootFolderPath, newFileName);


                Directory.CreateDirectory(wwwRootFolderPath);

                using (var fileStream = new FileStream(wwwRootFilePath, FileMode.Create))
                {
                    formData.File.CopyTo(fileStream);
                }

            }

            if (formData.Id == 0)
            {
                var festAddDto = new FestAddOrUpdateDto
                {
                    Id = formData.Id,
                    FestName = formData.FestName,
                    CityId = formData.CityId,
                    StartDate = formData.StartDate,
                    EndDate = formData.EndDate,
                    Description = formData.Description,
                    Location = formData.Location,
                    TicketPrice = formData.TicketPrice,
                    ImagePath = newFileName
                };

                var response = _FestService.AddFest(festAddDto);

                if(response.IsSucceed)
                {
                    return RedirectToAction("List");
                }
                else
                {
                    ViewBag.errorMessage = response.Message;

                    return View("Form", formData);
                }

            }
            else
            {
                var festEditDto = new FestAddOrUpdateDto
                {
                    Id = formData.Id,
                    FestName = formData.FestName,
                    CityId = formData.CityId,
                    StartDate = formData.StartDate,
                    EndDate = formData.EndDate,
                    Description = formData.Description,
                    Location = formData.Location,
                    TicketPrice = formData.TicketPrice,

                };

                if(formData.File!=null)
                {
                    festEditDto.ImagePath = newFileName;

                    _FestService.EditFest(festEditDto);

                    return RedirectToAction("List");
                }

            }


            return View();
        }

        public IActionResult Delete(int id)
        {
            _FestService.DeleteFest(id);

            return RedirectToAction("List");
        }


        public IActionResult Detail(int id)
        {
            var dto=_FestService.GetFestDetail(id);

            var viewModel = new FestDetailVM
            {
                Id = dto.Id,
                FestName = dto.FestName,
                CityName = dto.CityName,
                CountryName = dto.CountryName,
                StartDate = dto.StartDate,
                EndDate = dto.EndDate,
                CreatedDate = dto.CreatedDate,
                Description = dto.Description,
                FestDuration = dto.FestDuration,
                Location = dto.Location,
                Time = dto.Time,
                TicketPrice = dto.TicketPrice,
                IsActive = dto.IsActive
                
            };


            return PartialView(viewModel);
        }

    }
}

Fest.WebUI/Controllers/FestController.cs
using Fest.Business.Dtos.Comment;
using Fest.Business.Services;
using Fest.WebUI.Extensions;
using Fest.WebUI.Models.ViewModel.CommentVM;
using Fest.WebUI.Models.ViewModel.FestVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Fest.WebUI.Controllers
{
    public class FestController : Controller
    {
        private readonly IFestService _festService;

        private readonly IFestArtistService _festArtistService;

        private readonly ICommentService _commentService;

        public FestController(IFestService festService, IFestArtistService festArtistService, ICommentService commentService)
        {
            _festService = festService;
            _festArtistService = festArtistService;
            _commentService = commentService;
        }


        public IActionResult List()
        {
            var dtos = _festService.GetFestList();


            var firstFest = _festService.GetFestFirstData();


            ViewBag.firstData = firstFest;

            var viewModels = dtos.Select(x => new FestListVM
            {
                Id = x.Id,
                StartDate = x.StartDate,
                FestName = x.FestName,
                ImagePath = x.ImagePath,
                Description = x.Description,
                TicketPrice = x.TicketPrice,
                CityName = x.CityName,
                CountryName = x.CountryName

            }).ToList();


            return View(viewModels);
        }

        public IActionResult Detail(int id)
        {

            var festDetail = _festArtistService.GetFestArtistFullDetail(id);

            var viewModel = new FestArtistFullDetailVM
            {
                Id = id,

                FestName = festDetail.FestName,
                CityName = festDetail.CityName,
                CountryName = festDetail.CountryName,
                StartDate = festDetail.StartDate,
                EndDate = festDetail.EndDate,
                Description = festDetail.Description,
                Location = festDetail.Location,
                TicketPrice = festDetail.TicketPrice,
                IsActive = festDetail.IsActive,
                Artists = festDetail.Artists,
                ImagePath = festDetail.ImagePath,
                FestId = festDetail.FestId
            };


            return View(viewModel);
        }

        [Authorize(Roles = "admin, user")]
        [HttpPost]
        public IActionResult Comment(int festId, string content)
        {



            var userId = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value);

            var firstName = User.Claims.FirstOrDefault(x => x.Type == "firstName")?.Value;

            var lastName = User.Claims.FirstOrDefault(x => x.Type == "lastName")?.Value;

            var dto = new CommentDto
            {

                FestId = festId,
                AuthorName = firstName + " " + lastName,
                Status = false,
                Content = content,
                UserId = userId


            };


            _commentService.Comment(dto);

            return RedirectToAction("Detail", new { id = festId });
        }


    }
}

Fest.WebUI/Controllers/PaymentController.cs
using Fest.Business.Dtos.Payment;
using Fest.Business.Dtos.Ticket;
using Fest.Business.Services;
using Fest.WebUI.Models.ViewModel.PaymentVM;
using Fest.WebUI.Models.ViewModel.TicketVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Fest.WebUI.Controllers
{
    [Authorize(Roles = "admin, user")]
    public class PaymentController : Controller
    {

        private readonly ITicketService _ticketService;

        private readonly IPaymentService _paymentService;

        public PaymentController(ITicketService ticketService,IPaymentService paymentService)
        {
            _ticketService = ticketService;
            _paymentService = paymentService;
        }


        [HttpGet]
        public IActionResult Pay(int festId)
        {
            ViewBag.FestId = festId;

            return View(new PaymentViewModel());
        }
        [HttpPost]
        public IActionResult Pay(PaymentViewModel formData,int festId)
        {


            var userId = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value);

            ViewBag.FestId = festId;

            if (ModelState.IsValid)
            {
                var ticket = new TicketDto
                {
                    
                    FestId = festId,
                    Quantity = 1,
                    Status = true,
                    UserId = userId,
                    

                };

                

                int ticketCreated = _ticketService.TicketBuy(ticket,festId);

                if (ticketCreated != null)
                {

                    

                    var payment = new PaymentDto
                    {
                        
                        CardHolderName = formData.CardHolderName,
                        CardNumber = formData.CardNumber,
                        Cvv = formData.Cvv,
                        ExpirationDate=formData.CardExpirationDate,
                        TicketId=ticketCreated,
                        UserId=userId,
                    };

                    _paymentService.Payment(payment);


                    return RedirectToAction("Index", "Home");

                }


            }

            return View();
        }
    }
}

Fest.WebUI/Views/Fest/Detail.cshtml
@model FestArtistFullDetailVM



<style>
    <style >
    .artist-list {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        margin: 0;
        padding: 0;
        list-style: none;
    }

    .artist-list li {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin: 0 20px 40px;
    }

    .artist-info {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-bottom: 20px;
    }

    .artist-name {
        font-weight: bold;
        margin-bottom: 5px;
    }

    .artist-image {
        height: 120px;
        width: 120px;
        object-fit: cover;
        border-radius: 50%;
    }
</style>



<div style="margin-top:200px">


    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="#"><i class="fa fa-home"></i> Anasayfa</a>
                        <a href="#">Festival</a>
                        <span>

                                @if (Model.IsActive)
                                {
                                <p class="text-primary">
                                    Aktif Festival
                                </p>
                                }


                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->
    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__item">
                            <div class="blog__details__item__pic set-bg" data-setbg="/images/fests/@Model.ImagePath">
                                <a href="#"><i class="fa fa-share-alt"></i></a>
                            </div>
                            <div class="blog__details__item__text">
                                <span>Music festival</span>
                                <h3>
                                    Festival : @Model.FestName
                                </h3>
                                <div class="blog__details__item__widget">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <ul>

                                                <li>Başlangıç Tarihi : Başlangıç : @Model.StartDate</li>
                                                <li>Bitiş : @Model.EndDate</li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-6">
                                            <ul>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__desc">
                            <p>
                                Açıklama @Model.Description
                            </p>

                        </div>

                        <p>Festivalde Yer Alan Sanatçılar</p>

                        <div class="blog__details__quote">

                            <ul class="artist-list">
                                    @foreach (var item in Model.Artists)
                                    {
                                    <li>
                                        <div class="artist-info">
                                            <div class="artist-name">@item.NameAndLastName</div>
                                            <img class="artist-image" src="~/images/artists/@item.ImagePath" />
                                        </div>
                                    </li>
                                    }
                            </ul>
                            <i class="fa fa-quote-right"></i>
                        </div>

                        <div class="blog__details__desc">
                            <p>

                                Yer Bilgisi : @Model.Location
                            </p>
                            <p>
                                Ülke :  @Model.CountryName , Şehir : @Model.CityName
                            </p>
                        </div>
                        <div class="blog__details__tags">
                            <a href="#">Music</a>
                            <a href="#">Festival</a>
                            <a href="#">Tinternational</a>
                            <a href="#">Event</a>
                        </div>

                        <div class="blog__details__form">
                            <div class="blog__details__form__title">
                                <h4>Yorum Yap</h4>
                            </div>
                            <form method="post" asp-controller="Fest" asp-action="Comment">
                                <div class="input__list">





                                    <input type="hidden" value="@Model.FestId" name="festId" />


                                </div>
                                <textarea name="content" placeholder="Yorum"></textarea>
                                <button type="submit" class="site-btn">GÖNDER</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__item">
                            <div class="blog__sidebar__title">
                                <h4>Satın Al</h4>
                            </div>
                            <p>Bilet Fiyatı : @Model.TicketPrice</p>
                            <form asp-controller="Payment" asp-action="Pay" method="get">

                                <input type="hidden" name="festId" value="@Model.FestId" />

                                <button type="submit" class="site-btn">Ödeme Yap</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

</div>


<!-- Blog Details Section End -->
<!-- Footer Section Begin -->
<footer class="footer footer--normal spad set-bg" data-setbg="img/footer-bg.png">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="footer__address">
                    <ul>
                        <li>
                            <i class="fa fa-phone"></i>
                            <p>Phone</p>
                            <h6>1-677-124-44227</h6>
                        </li>
                        <li>
                            <i class="fa fa-envelope"></i>
                            <p>Email</p>
                            <h6>DJ.Music@gmail.com</h6>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1 col-md-6">
                <div class="footer__social">
                    <h2>DJoz</h2>
                    <div class="footer__social__links">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6">
                <div class="footer__newslatter">
                    <h4>Stay With me</h4>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit"><i class="fa fa-send-o"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</footer>

Fest.WebUI/Views/Fest/List.cshtml
@model List<FestListVM>


<section class="countdown countdown--page spad set-bg" data-setbg="/images/fests/@ViewBag.firstData.ImagePath">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="countdown__text">
                    <h1>@ViewBag.firstData.FestName</h1>
                    <h4>Başlayacak Olan Festival</h4>
                </div>
                <div class="countdown__timer" id="countdown-time">
                    <div class="countdown__item">
                        <span>20</span>
                        <p>days</p>
                    </div>
                    <div class="countdown__item">
                        <span>45</span>
                        <p>hours</p>
                    </div>
                    <div class="countdown__item">
                        <span>18</span>
                        <p>minutes</p>
                    </div>
                    <div class="countdown__item">
                        <span>09</span>
                        <p>@ViewBag.firstData.StartDate</p>
                    </div>
                </div>
                <div class="buy__tickets">
                    <a href="#" class="primary-btn">Buy tickets</a>

                    <a asp-controller="Fest" asp-action="Detail" asp-route-id="@ViewBag.firstData.Id" class="primary-btn ">Bilet Al</a>

                </div>
            </div>
        </div>
    </div>
</section>



<section class="tours spad">
    <div class="container">

        @foreach (var item in Model)
        {
            <div class="row">




                <div class="col-lg-6 order-lg-1">
                    <div class="tours__item__text">
                        <h2>@item.StartDate</h2>
                        <div class="tours__text__widget">
                            <ul>
                                <li>
                                    <i class="fa fa-clock-o"></i>
                                    <span>8:00pm</span>
                                    <span>Dec 15, 2019</span>
                                </li>
                                <li>
                                    <i class="fa fa-map-marker"></i>
                                    @item.CountryName , @item.CityName
                                </li>
                            </ul>
                            <div class="price">$ @item.TicketPrice</div>
                        </div>
                        <div class="tours__text__desc">

                            <p>
                                @item.Description
                            </p>
                        </div>
                        <a asp-controller="Fest" asp-action="Detail" asp-route-id="@item.Id" class="primary-btn border-btn">Bilet Al</a>
                    </div>
                </div>


                <div class="col-lg-6 order-lg-6">
                    <div class="tours__item__pic tours__item__pic--last">
                        <img style="height:400px;width:180px" src="~/images/fests/@item.ImagePath" alt="">
                    </div>
                </div>



            </div>


            <br />

            <br />

            <br />

        }






    </div>
</section>






<footer class="footer footer--normal spad set-bg" data-setbg="/templates/user/img/footer-bg.png">


    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="footer__address">
                    <ul>
                        <li>
                            <i class="fa fa-phone"></i>
                            <p>Phone</p>
                            <h6>1-677-124-44227</h6>
                        </li>
                        <li>
                            <i class="fa fa-envelope"></i>
                            <p>Email</p>
                            <h6>DJ.Music@gmail.com</h6>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1 col-md-6">
                <div class="footer__social">
                    <h2>DJoz</h2>
                    <div class="footer__social__links">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6">
                <div class="footer__newslatter">
                    <h4>Stay With me</h4>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit"><i class="fa fa-send-o"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</footer>