Fest.WebUI/Controllers/AuthController.cs
using Fest.Business.Dtos.User;
using Fest.Business.Services;
using Fest.WebUI.Models.ViewModel.UserVM;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Fest.WebUI.Controllers
{
    public class AuthController : Controller
    {

        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterVM formData)
        {

            

            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            var userDto = new RegisterDto()
            {
                Name = formData.Name.Trim(),
                LastName = formData.LastName.Trim(),
                Address = formData.Address.Trim(),
                Email = formData.Email.Trim(),
                Phone = formData.Phone.Trim(),
                Password = formData.Password.Trim(),

            };


            var response = _userService.AddUser(userDto);


            if (response.IsSucceed)
            {
                return RedirectToAction("index", "home");
            }
            else
            {
                ViewBag.errorMessage = response.Message;
                return View(formData);
            }

        }


        public async Task<IActionResult> Login(LoginVM formData)
        {
            var loginDto = new LoginDto()
            {
                Email = formData.Email.Trim(),
                Password = formData.Password.Trim(),
            };

            var user=_userService.Login(loginDto);

            if(user is null)
            {
                TempData["LoginMessage"] = "Kullanıcı Adı Veya Parolayı Yanlış Girdiniz";
                return RedirectToAction("index", "home");
            }

            var claims = new List<Claim>();

            claims.Add(new Claim("id", user.Id.ToString()));
            claims.Add(new Claim("email", user.Email));
            claims.Add(new Claim("firstName", user.Name));
            claims.Add(new Claim("lastName", user.LastName));
            claims.Add(new Claim("userType", user.UserType.ToString()));

            claims.Add(new Claim(ClaimTypes.Role, user.UserType.ToString()));

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var autProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(24))
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), autProperties);

            return RedirectToAction("index", "home");

            


        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("index", "home");
        }

        

        

    }
}

Fest.WebUI/Controllers/BlogController.cs
using Fest.Business.Services;
using Fest.WebUI.Models.ViewModel.BlogVM;
using Microsoft.AspNetCore.Mvc;

namespace Fest.WebUI.Controllers
{
    public class BlogController : Controller
    {

        private readonly IBlogService _blogService;

        public BlogController(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public IActionResult BlogList()
        {

            var blogDtoList=_blogService.GetBlogList();


            var blogViewModel = blogDtoList.Select(x => new BlogListVM
            {
                Id = x.Id,
                Title = x.Title,
                Content = x.Content,
                ImagePath = x.ImagePath,
                CreatedDate = x.CreatedDate
            }).ToList();

            return View(blogViewModel);
        }

        public IActionResult BlogDetail(int id)
        {

            var dto=_blogService.GetBlogDetail(id);

            var viewModel = new BlogDetailVM
            {
                Title = dto.Title,
                Content = dto.Content,
                CreatedDate = dto.CreatedDate,
                ImagePath = dto.ImagePath,
                ReadCount = dto.ReadCount
            };

            var dtos = _blogService.GetLastDataBlogs();

            var viewModels = dtos.Select(x => new BlogListVM
            {
                Id=x.Id,
                Title = x.Title,
                Content = x.Content,
                CreatedDate = x.CreatedDate,
                ImagePath = x.ImagePath,
            }).ToList();

            ViewBag.LastDataBlogs=viewModels;

            return View(viewModel);
        }

    }
}

Fest.WebUI/Controllers/FestController.cs
using Fest.Business.Dtos.Comment;
using Fest.Business.Services;
using Fest.WebUI.Extensions;
using Fest.WebUI.Models.ViewModel.CommentVM;
using Fest.WebUI.Models.ViewModel.FestVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Fest.WebUI.Controllers
{
    public class FestController : Controller
    {
        private readonly IFestService _festService;

        private readonly IFestArtistService _festArtistService;

        private readonly ICommentService _commentService;

        public FestController(IFestService festService, IFestArtistService festArtistService, ICommentService commentService)
        {
            _festService = festService;
            _festArtistService = festArtistService;
            _commentService = commentService;
        }


        public IActionResult List()
        {
            var dtos = _festService.GetFestList();


            var firstFest = _festService.GetFestFirstData();


            ViewBag.firstData = firstFest;

            var viewModels = dtos.Select(x => new FestListVM
            {
                Id = x.Id,
                StartDate = x.StartDate,
                FestName = x.FestName,
                ImagePath = x.ImagePath,
                Description = x.Description,
                TicketPrice = x.TicketPrice,
                CityName = x.CityName,
                CountryName = x.CountryName

            }).ToList();


            return View(viewModels);
        }

        public IActionResult Detail(int id)
        {

            var festDetail = _festArtistService.GetFestArtistFullDetail(id);

            var viewModel = new FestArtistFullDetailVM
            {
                Id = id,

                FestName = festDetail.FestName,
                CityName = festDetail.CityName,
                CountryName = festDetail.CountryName,
                StartDate = festDetail.StartDate,
                EndDate = festDetail.EndDate,
                Description = festDetail.Description,
                Location = festDetail.Location,
                TicketPrice = festDetail.TicketPrice,
                IsActive = festDetail.IsActive,
                Artists = festDetail.Artists,
                ImagePath = festDetail.ImagePath,
                FestId = festDetail.FestId
            };


            return View(viewModel);
        }

        [Authorize(Roles = "admin, user")]
        [HttpPost]
        public IActionResult Comment(int festId, string content)
        {



            var userId = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value);

            var firstName = User.Claims.FirstOrDefault(x => x.Type == "firstName")?.Value;

            var lastName = User.Claims.FirstOrDefault(x => x.Type == "lastName")?.Value;

            var dto = new CommentDto
            {

                FestId = festId,
                AuthorName = firstName + " " + lastName,
                Status = false,
                Content = content,
                UserId = userId


            };


            _commentService.Comment(dto);

            return RedirectToAction("Detail", new { id = festId });
        }


    }
}

Fest.WebUI/Views/Shared/_FooterPartial.cshtml
<footer class="footer spad set-bg" data-setbg="img/footer-bg.png">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="footer__address">
                    <ul>
                        <li>
                            <i class="fa fa-phone"></i>
                            <p>Phone</p>
                            <h6>1-677-124-44227</h6>
                        </li>
                        <li>
                            <i class="fa fa-envelope"></i>
                            <p>Email</p>
                            <h6>DJ.Music@gmail.com</h6>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1 col-md-6">
                <div class="footer__social">
                    <h2>DJoz</h2>
                    <div class="footer__social__links">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6">
                <div class="footer__newslatter">
                    <h4>Stay With me</h4>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit"><i class="fa fa-send-o"></i></button>
                    </form>
                </div>
            </div>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        <div class="footer__copyright__text">
            <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
        </div>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    </div>
</footer>

Fest.WebUI/Views/Shared/_Layout.cshtml
@using Fest.WebUI.Extensions;

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="DJoz Template">
    <meta name="keywords" content="DJoz, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Music FEST </title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <style>
        .ml-auto {
            margin-left: auto !important;
        }

        .form-inline {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
        }

        form > div > .d-flex > input,
        form > div > .d-flex > button {
            margin-right: 6px;
        }
    </style>



    <partial name="_StylePartial" />

</head>

@{
    var name = User.Claims.FirstOrDefault(x => x.Type == "firstName")?.Value;
    var lastName = User.Claims.FirstOrDefault(x => x.Type == "lastName")?.Value;
}

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>



    <!-- Header Section Begin -->
    <header class="header ">



        <div class="col-5 ml-auto">




            @if (!User.IsLogged())
            {
                <div class="d-none" id="login">

                    <partial name="_LoginPartial" model="new LoginVM()" />

                </div>


                <div class="col-5 ml-auto">


                    <div class="text-end mt-3" id="welcome">
                        <button id="btnGirisYap" type="button" class="btn btn-outline-light me-2">Giriş Yap</button>
                        <a asp-controller="Auth" asp-action="Register" class="btn btn-warning">Kayıt Ol</a>
                    </div>
                </div>


            }
            

        </div>

        <div class="container">



            <div class="row">



                <div class="col-lg-2 col-md-2">
                    <div class="header__logo">
                        <a asp-controller="Home" asp-action="Index"><img src="~/Templates/User/img/events/My+House+-+Flat+B+(2).png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10 col-md-10">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="./index.html">Anasayfa</a></li>
                                <li><a asp-controller="Fest" asp-action="List">Festivaller</a></li>
                                <li><a href="./discography.html">Keşfet</a></li>

                                <li><a asp-controller="Blog" asp-action="BlogList">Blog</a></li>
                                <li>
                                    @if (User.IsLogged())
                                    {
                                        <a href="#">Hesabım</a>



                                        <ul class="dropdown">

                                            @if (User.IsLogged())
                                            {
                                                <li>

                                                    <a> @name @lastName</a>

                                                    <hr style="border: none;
  border-bottom: 1px dashed #999;">

                                                </li>
                                            }




                                            <li><a asp-controller="Account" asp-action="Profile">Profil</a></li>
                                            <li><a asp-controller="Account" asp-action="Tickets">Biletlerim</a></li>
                                            <li><a href="#">Bilgilendirme</a> </li>

                                            @if (User.IsAdmin())
                                            {
                                                <li>
                                                    <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" asp-action="">Admin Panel</a>



                                                </li>
                                            }



                                            <li>
                                                <hr style="border: none;
  border-bottom: 1px dashed #999;">
                                            </li>

                                            <li><a asp-controller="Auth" asp-action="Logout">Çıkış Yap</a></li>
                                        </ul>
                                    }
                                </li>

                            </ul>
                        </nav>


                        <div class="header__right__social">


                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"> <i class="fa fa-facebook"></i> </a>

                        </div>


                    </div>
                </div>
            </div>


            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header Section End -->
    <!-- Hero Section Begin -->



    <div>

        @RenderBody()

    </div>









    @*<partial name="_FooterPartial" />*@
    <!-- Footer Section End -->
    <!-- Js Plugins -->



    <partial name="_ModalDetailPartial" />

    <partial name="_ScriptPartial" />

    <script>

        $('#btnGirisYap').click(function () {

            $('#welcome').addClass('d-none');
            $('#login').removeClass('d-none');
        })

        $('#btnGirisIptal').click(function () {
            $('#welcome').removeClass('d-none');
            $('#login').addClass('d-none');
        })

        @if (!string.IsNullOrWhiteSpace(TempData["LoginMessage"]?.ToString()))
        {
            @:toastr.error("@TempData["LoginMessage"].ToString()")
        }


    </script>


    @await RenderSectionAsync("Scripts" , required:false)




</body>

</html>

Fest.WebUI/Views/Shared/_ScriptPartial.cshtml
<script src="~/Templates/User/js/jquery-3.3.1.min.js"></script>
<script src="~/Templates/User/js/bootstrap.min.js"></script>
<script src="~/Templates/User/js/jquery.magnific-popup.min.js"></script>
<script src="~/Templates/User/js/jquery.nicescroll.min.js"></script>
<script src="~/Templates/User/js/jquery.barfiller.js"></script>
<script src="~/Templates/User/js/jquery.countdown.min.js"></script>
<script src="~/Templates/User/js/jquery.slicknav.js"></script>
<script src="~/Templates/User/js/owl.carousel.min.js"></script>
<script src="~/Templates/User/js/main.js"></script>

<!-- Music Plugin -->
<script src="~/Templates/User/js/jquery.jplayer.min.js"></script>
<script src="~/Templates/User/js/jplayerInit.js"></script>

Fest.WebUI/Views/Shared/_StylePartial.cshtml
<link rel="stylesheet" href="~/Templates/User/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/barfiller.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/nowfont.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/rockville.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/magnific-popup.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/owl.carousel.min.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/slicknav.min.css" type="text/css">
<link rel="stylesheet" href="~/Templates/User/css/style.css" type="text/css">

<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css" type="text/css">