Fest.WebUI/Areas/Admin/Controllers/ArtistController.cs
using Fest.Business.Dtos.Artist;
using Fest.Business.Services;
using Fest.WebUI.Areas.Admin.Models.ViewModel.ArtistViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Net.WebSockets;
using System.Security.AccessControl;
using X.PagedList;

namespace Fest.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class ArtistController : Controller
    {
        private readonly IArtistService _artistService;

        private readonly IWebHostEnvironment _environment;

        public ArtistController(IArtistService artistService, IWebHostEnvironment environment)
        {
            _artistService = artistService;
            _environment = environment;
        }


        public IActionResult List(string search, int page = 1)
        {



            if (string.IsNullOrEmpty(search))
            {
                var artistDtoList = _artistService.GetArtistList();

                var viewModel = artistDtoList.Select(x => new ArtistListVM
                {
                    Id = x.Id,
                    Description = x.Description,
                    BirthDate = x.BirthDate,
                    ImagePath = x.ImagePath,
                    NameAndLastName = x.NameAndLastName,
                }).ToList().ToPagedList(page, 4);

                ViewBag.Count = viewModel.Count;

                return View(viewModel);

            }
            else
            {

                var dtoList = _artistService.GetArtistSearchList(search);

                var searchViewModel = dtoList.Select(x => new ArtistListVM
                {
                    BirthDate = x.BirthDate,
                    Description = x.Description,
                    Id = x.Id,
                    ImagePath = x.ImagePath,
                    NameAndLastName = x.NameAndLastName
                }).ToList().ToPagedList(page, 4);


                ViewBag.Count = searchViewModel.Count;

                return View(searchViewModel);
            }



        }
        [HttpGet]
        public IActionResult New(int? id)
        {

            if (id != null)
            {
                var artistDto = _artistService.GetArtist(id.Value);

                var viewModel = new ArtistAddOrUpdateVM()
                {
                    Id = artistDto.Id,
                    Name = artistDto.Name,
                    LastName = artistDto.LastName,
                    BirthDate = artistDto.BirthDate,
                    Description = artistDto.Description,
                    InstagramUrl = artistDto.InstagramUrl,
                    LinkedInUrl = artistDto.LinkedInUrl,
                    TwitterUrl = artistDto.TwitterUrl,
                    YoutubeUrl = artistDto.YoutubeUrl

                };

                ViewBag.ImagePath = artistDto.ImagePath;

                return View("Form", viewModel);


            }
            else
            {
                return View("Form", new ArtistAddOrUpdateVM());
            }


        }

        [HttpPost]
        public IActionResult Save(ArtistAddOrUpdateVM formData)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", formData);
            }

            var newFileName = "";


            if (formData.File != null)
            {
                var allowedFileContentTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };

                var allowedFileExtensions = new string[] { ".jpeg", ".png", ".jpg", ".jfif" };


                var fileContentType = formData.File.ContentType;

                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(formData.File.FileName);

                var fileExtension = Path.GetExtension(formData.File.FileName);

                if (!allowedFileContentTypes.Contains(fileContentType) || !allowedFileExtensions.Contains(fileExtension))
                {

                    ViewBag.fileError = "Lütfen jpg jpeg png jfif uzantılı bir dosya türü seçiniz";

                    return View("Form", formData);
                }

                newFileName = fileNameWithoutExtension + "-" + Guid.NewGuid() + fileExtension;

                var folderPath = Path.Combine("images", "artists");

                var wwwRootFolderPath = Path.Combine(_environment.WebRootPath, folderPath);

                var wwwRootFilePath = Path.Combine(wwwRootFolderPath, newFileName);


                Directory.CreateDirectory(wwwRootFolderPath);

                using (var fileStream = new FileStream(wwwRootFilePath, FileMode.Create))
                {
                    formData.File.CopyTo(fileStream);
                }

            }

            if (formData.Id == 0)
            {
                var artistDto = new ArtistAddOrUpdateDto()
                {
                    Id = formData.Id,
                    Name = formData.Name,
                    LastName = formData.LastName,
                    BirthDate = formData.BirthDate,
                    Description = formData.Description,
                    InstagramUrl = formData.InstagramUrl,
                    LinkedInUrl = formData.LinkedInUrl,
                    TwitterUrl = formData.TwitterUrl,
                    YoutubeUrl = formData.YoutubeUrl,
                    ImagePath = newFileName

                };

                var response = _artistService.AddArtist(artistDto);


                if (response.IsSucceed)
                {
                    return RedirectToAction("List");
                }
                else
                {
                    ViewBag.errorMessage = response.Message;

                    return View("Form", formData);
                }
            }
            else
            {
                var artistDto = new ArtistAddOrUpdateDto()
                {
                    Id = formData.Id,
                    Name = formData.Name,
                    LastName = formData.LastName,
                    BirthDate = formData.BirthDate,
                    Description = formData.Description,
                    InstagramUrl = formData.InstagramUrl,
                    LinkedInUrl = formData.LinkedInUrl,
                    TwitterUrl = formData.TwitterUrl,
                    YoutubeUrl = formData.YoutubeUrl

                };

                if (formData.File != null)
                {
                    artistDto.ImagePath = newFileName;
                }

                _artistService.EditArtist(artistDto);

            }

            return RedirectToAction("List");


        }


        public IActionResult Delete(int id)
        {

            _artistService.DeleteArtist(id);

            return RedirectToAction("List");

        }


        public IActionResult Detail(int id)
        {

            var dto = _artistService.GetArtistDetail(id);


            var viewModel = new ArtistDetailVM
            {
                Name = dto.Name,
                LastName = dto.LastName,
                Age = dto.Age,
                ImagePath = dto.ImagePath,
                CreatedDate = dto.CreatedDate,
                Description = dto.Description,
                InstagramUrl = dto.InstagramUrl,
                LinkedInUrl = dto.LinkedInUrl,
                TwitterUrl = dto.TwitterUrl,
                YoutubeUrl = dto.YoutubeUrl,
                IsActive = dto.IsActive
            };



            return PartialView(viewModel);
        }

    }
}

Fest.WebUI/Areas/Admin/Controllers/ArtistMusicTypeController.cs
using Fest.Business.Dtos.ArtistMusicType;
using Fest.Business.Services;
using Fest.WebUI.Areas.Admin.Models.ViewModel.ArtistMusicTypeViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using X.PagedList;

namespace Fest.WebUI.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class ArtistMusicTypeController : Controller
    { 

        private readonly IArtistMusicTypeService _artistMusicTypeService;

        private readonly IArtistService _artistService;

        private readonly IMusicTypeService _musicTypeService;

        public ArtistMusicTypeController(IArtistService artistService , IMusicTypeService musicTypeService,IArtistMusicTypeService artistMusicTypeService)
        {
            
            _artistService = artistService;
            _musicTypeService = musicTypeService;
            _artistMusicTypeService = artistMusicTypeService;
        }

        public IActionResult List(string search , int page=1)
        {

            if (string.IsNullOrEmpty(search))
            {
                var dtos = _artistMusicTypeService.GetArtistMusicTypeList();

                var viewModel = dtos.Select(x => new ArtistMusicTypeListVM
                {
                    SongName = x.SongName,
                    ArtistNameAndLastName = x.ArtistNameAndLastName,
                    MusicType = x.MusicType,
                    ArtistId = x.ArtistId,
                    MusicTypeId = x.MusicTypeId,
                    ImagePath = x.ImagePath

                }).ToList().ToPagedList(page,4);

                ViewBag.artistMusicType = viewModel.Count;
                

                 return View(viewModel);
            }
            else
            {
                var searchDtos = _artistMusicTypeService.GetArtistMusicTypeSearchList(search);

                var searchViewModel = searchDtos.Select(x => new ArtistMusicTypeListVM
                {
                    SongName = x.SongName,
                    ArtistNameAndLastName = x.ArtistNameAndLastName,
                    MusicType = x.MusicType,
                    ArtistId = x.ArtistId,
                    MusicTypeId = x.MusicTypeId,
                    ImagePath = x.ImagePath
                }).ToList().ToPagedList(page, 4);


                ViewBag.artistMusicType=searchViewModel.Count;

                return View(searchViewModel);


            }

            


           
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Artists=_artistService.GetArtistList();

            ViewBag.musicTypes=_musicTypeService.GetMusicTypes();


            return View(new ArtistMusicTypeAddOrUpdateVM());
        }

        [HttpPost]
        public IActionResult Add(ArtistMusicTypeAddOrUpdateVM formData)
        {

            var dto = new ArtistMusicTypeAddOrUpdateDto()
            {
                ArtistId = formData.ArtistId,
                MusicTypeId = formData.MusicTypeId,
            };

            _artistMusicTypeService.AddArtistMusicType(dto);

            return RedirectToAction("List");
        }


        public IActionResult Detail(int artistId,int musicTypeId)
        {
            var artistMusicType=_artistMusicTypeService.GetArtistMusicTypeDetail(artistId, musicTypeId);


            var viewModel = new ArtistMusicTypeDetailVM
            {
                SongName = artistMusicType.SongName,
                NameAndLastName = artistMusicType.NameAndLastName,
                Instagram = artistMusicType.Instagram,
                MusicType = artistMusicType.MusicType,
                LinkedIn = artistMusicType.LinkedIn,
                Youtube = artistMusicType.Youtube,
                Twitter = artistMusicType.Twitter,
                IsActive = artistMusicType.IsActive,
                ImagePath=artistMusicType.ImagePath
                
            };


            return PartialView(viewModel);

        }

        [HttpPost]
        public IActionResult Delete(int artistId,int musicTypeId)
        {
            _artistMusicTypeService.DeleteArtistMusicType(artistId, musicTypeId);

            return RedirectToAction("List");
        }



    }
}

Fest.WebUI/Areas/Admin/Views/ArtistMusicType/Add.cshtml
@model ArtistMusicTypeAddOrUpdateVM

<div class="container" style="padding-top:40px">

    <div class="row">

        <div class="col-md-8 offset-2">

            <div class="card" style="border:solid 2px">

                <div class="card-header fw-bold fs-5" style="text-align:center">

                    <p class="text-bg-light">

                        <span>

                            @(Model.ArtistId == 0 ? "Sanatçı - Müzik Ekleme Formu" : "Sanatçı - Müzik Düzenleme Formu")

                        </span>

                    </p>
                </div>

                <div class="card-body">

                    <form method="post" asp-area="Admin" asp-controller="ArtistMusicType" asp-action="Add">



                        @if (!string.IsNullOrWhiteSpace(ViewBag.errorMessage))
                        {

                            <div class="alert alert-danger">
                                @ViewBag.errorMessage
                            </div>

                        }

                        @*<input asp-for="Id" type="hidden" />*@


                        <div class="form-group mb-2">

                            <label asp-for="ArtistId"></label>

                            <select asp-items="@(new SelectList(ViewBag.Artists,"Id","NameAndLastName"))" class="form-control" type="text"
                                    asp-for="ArtistId">

                                    <option value="" >Seçiniz...

                                    </option>
                            </select>

                            <span asp-validation-for="ArtistId" class="text-danger fw-bold"></span>



                        </div>

                        <div class="form-group mb-2">

                            <label asp-for="MusicTypeId"></label>

                            <select asp-items="@(new SelectList(ViewBag.musicTypes,"Id","MusicName"))" class="form-control" type="text"
                                    asp-for="MusicTypeId">

                                    <option value="">Seçiniz...

                                    </option>

                            </select>

                            <span asp-validation-for="MusicTypeId" class="text-danger fw-bold"></span>



                        </div>




                        <button type="submit" class="btn btn-success mt-3 float-end">
                            @(Model.ArtistId == 0 ? "Ekle" : "Güncelle")  
                        </button>

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>

Fest.WebUI/Areas/Admin/Views/ArtistMusicType/Detail.cshtml
@model ArtistMusicTypeDetailVM

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-A+oz9pTBz3e29JmcbjZLWuZEBmflwDwz1JDb2y7Vqx+d9XGy7VfhdZxlQDZ+eA5JLhjKTCn5Ed5P5MMihX9XKg==" crossorigin="anonymous" referrerpolicy="no-referrer" />


<div class="modal-header">

    @if (Model.IsActive)
    {
        <h6 style="color:green">Aktif Kayıt</h6>
    }
    else
    {
        <h6 style="color:red">Kayıt Aktif Değil</h6>
    }

    <hr />





    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>



</div>
<div class="modal-body">

    


    <br />

    @if (string.IsNullOrWhiteSpace(Model.ImagePath))
    {
        <img style="width:100px;height:100px" src="~/images/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg" />
    }
    else
    {
        <a style="width:80px;height:80px" href="~/images/artists/@Model.ImagePath" data-title="@Model.NameAndLastName">

            <img src="~/images/artists/@Model.ImagePath" alt="@Model.NameAndLastName" style="width:100px;height:100px" />

        </a>
    }


    <h6>Sanatçı : @Model.NameAndLastName</h6>

    <br />

    <h6>Müzik-Şarkı Adı : @Model.SongName</h6>

    <br />

    <h6>Müzik Şarkı Tipi : @Model.MusicType</h6>

    <br />

    <h6>
        Sanatçı Sosyal Medya Hesapları :

        <a href="@Model.Youtube">
            <i class="bi bi-youtube"></i>

        </a>

        <a href="@Model.Twitter">
            <i class="bi bi-twitter"></i>

        </a>

        <a href="@Model.LinkedIn">
            <i class="bi bi-linkedin"></i>

        </a>

        <a href="@Model.Instagram">
            <i class="bi bi-instagram"></i>

        </a>


    </h6>



    <hr />

    

</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>

</div>

Fest.WebUI/Areas/Admin/Views/ArtistMusicType/List.cshtml
@model PagedList<ArtistMusicTypeListVM>

<div class="container">


    <div class="row">

        <div class="col-sm-11">

            <div class="text-center">

                <h2 style="font-family:'Italic Outline Art';" class="text-secondary">Sanatçı - Müzik</h2>
            </div>


            <div style="padding-top:50px">


                <div style="margin-bottom:15px">


                    <div class="float-start">
                        <form>
                            <div class="btn-group">
                                <input class="form-control" type="text" placeholder="Arama Yap ...." name="search" style="display: inline-block; width: 80%;" />
                                <input class="p-2 ml-3 btn btn-sm btn-primary" type="submit" value="Ara" style="display: inline-block; width: 20%;" />
                            </div>
                        </form>

                    </div>

                </div>


                <div class="float-end">
                    <a asp-area="Admin" asp-controller="ArtistMusicType" asp-action="Add" class="btn btn-link">

                        <i class="bi bi-plus-circle-fill">
                            Yeni Sanatçı-Müzik
                        </i>

                    </a>
                </div>


                <table id="myTable" class="table table-bordered table-striped">

                    <thead>

                        <tr>
                            <th></th>
                            <th>Sanatçı</th>
                            <th>Müzik</th>
                            <th>Müzik Türü</th>
                            <th></th>

                            <th></th>
                        </tr>

                    </thead>

                    <tbody>

                        @if (Model != null)
                        {
                            @for (int i = 0; i < Model.Count; i++)
                            {

                                <tr class="table">


                                    <td>

                                        @if (string.IsNullOrWhiteSpace(Model[i].ImagePath))
                                        {
                                            <img style="width:100px;height:100px" src="~/images/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg" />
                                        }
                                        else
                                        {
                                            <a style="width:80px;height:80px" href="~/images/artists/@Model[i].ImagePath" data-lightbox="@Model[i].Id" data-title="@Model[i].ArtistNameAndLastName">

                                                <img src="~/images/artists/@Model[i].ImagePath" alt="@Model[i].ArtistNameAndLastName" style="width:100px;height:100px" />

                                            </a>
                                        }

                                    </td>



                                    <td>@Model[i].ArtistNameAndLastName</td>
                                    <td class="mt-4">@Model[i].SongName</td>
                                    <td class="mt-4">@Model[i].MusicType</td>



                                    <td>



                                        <button class="btn btn-sm btn-secondary modalButton" onclick="openModal(@Model[i].ArtistId,@Model[i].MusicTypeId)">
                                            <i class="bi-search"></i>
                                            Detay


                                        </button>






                                        <a style="margin-left:3px" asp-area="Admin" asp-controller="Artist" asp-action="New" asp-route-id="@Model[i].Id" class="btn btn-sm btn-primary" alt="Güncelle">
                                            <i class="bi bi-pencil-fill">Güncelle</i>
                                        </a>


                                        


                                        


                                    </td>


                                </tr>

                            }
                        }
                        else
                        {
                            <tr class="container">
                                <td>Henüz Bir Kayıt Bulunamadı</td>
                            </tr>
                        }


                    </tbody>

                </table>


                <div style="margin-top:30px">

                    <div class="col-md-3
" style="margin-left:auto;text-align:right">

                        @Html.PagedListPager((IPagedList)Model,page=>Url.Action("List","ArtistMusicType",new {page=page}),
                        new PagedListRenderOptions {

                        LiElementClasses=new List<string>
                        {"page-link"}
                        })




                    </div>

                </div>

            </div>


        </div>


        <div>
            <p class="text-secondary">Toplam : @ViewBag.artistMusicType Kayıt Bulundu.</p>
        </div>

    </div>



</div>




@section Scripts{

    <script>


        function openModal(artistId, musicTypeId) {

            $.ajax({

                url: '/Admin/ArtistMusicType/Detail',
                type: 'POST',
                data: { artistId: artistId, musicTypeId: musicTypeId },
                success: function (result) {

                    $("#modalContent").html(result);
                    $("#modalContainer").modal("show");
                }

            })

        }


                        //$(".modalButton").click(function () {
                        //    // AJAX isteği yapın

                        //    var Id = $(this).data("id")

                        //    $.ajax({
                        //        url: "/Admin/User/Detail/" + Id,
                        //        type: "GET",
                        //        success: function (result) {
                        //            // Detail sayfasındaki içeriği alın
                        //            $("#modalContent").html(result);
                        //            // Modalı açın
                        //            $("#modalContainer").modal("show");
                        //        }
                        //    });
                        //});







    </script>




}